### ISSUE TITLE
Update the README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by YaMo97** [UdacityAndroidBasicsScholarship/design-villa#40]
Update the README.md for better explanation of the Project. 

Also update CONTRIBUTING.md for Contribution Guidelines.

Other repos can be considered for ideas. #

**Comment by amy6** [comment]
Hi @YaMo97 thank you for reviewing our guidelines! We have updated README.md and CONTRIBUTING.md as suggested. Please take a look and do share your feedback with us!
